### ISSUE TITLE
Publish to NPM

### ISSUE THREAD

**Issue by logasja** [lukas2005/-types-orbit-db#32]
Is there a reason this package isn't published to npm? I only ask because I used pnpm and it has some issues with using git repos as packages.

**Comment by tabcat** [comment]
Any idea how to publish under the @types scope? @chrispanag

**Comment by tabcat** [comment]
https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html seems relevant

**Comment by chrispanag** [comment]
> Any idea how to publish under the @types scope? @chrispanag

the @types scope is just an organisation on npm that's managed by the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) repository. Any package that is added to this repo, is published under the @types scope on npm. 

You can read more here: https://github.com/DefinitelyTyped/DefinitelyTyped#faq

**Comment by tabcat** [comment]
I'm thinking we will probably include definition files in the source via jsdoc similar to ipfs so we can also generate API docs with https://typedoc.org/ so it may not be worth publishing this now.
